### ISSUE TITLE
Unable to login to MyCP

### ISSUE THREAD

**Issue by kaniick** [hyperhost/whmcs-provisioning-module#3]
When the client purchases a product the customer is created with a HH ID which is sent to the module. The Instance is created and linked to the customer. Everything is activated. When the client attempts to click on the Login to MyCP on the product/service side of WHMCS the following error is provided; Action Failed Unable to auto-login. Please contact support.

This problem is also the same for the Admin side the following error is provided when attempting to login to the clients MyCP from the WHMCS backend of the product overview; Module Command Error
Unable to auto-login.

**Comment by tonycodes** [comment]
Hi @kaniick, 

This has now been fixed :)
